title: Rooted
description: "CTF writeups, infosec resources, and projects."
author:
  name: "alex"
  email: "alexmcculley19@gmail.com"
  url: "https://amcculley1894.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "alex"
year : "2020"
